# web服务
server:
    port: 8080

# log4j2
logging:
    config: classpath:log4j2.yml

# spring
spring:
    mvc:
        # 关闭异常自动日志
        log-resolved-exception: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            # 访问控制界面的账号密码
            stat-view-servlet:
                enabled: true
                login-username: admin
                login-password: admin
                deny:
                allow:
                url-pattern: /druid/*
                reset-enable: true
            web-stat-filter:
                enabled: true
                url-pattern: /api/*
                exclusions: .gif,.html
        dynamic:
            primary: master
            strict: false
            druid:
                # 连接池容量配置
                initial-size: 40
                min-idle: 20
                max-active: 60

                # 获取链接时最大等待时间，单位：毫秒
                max-wait: 6000

                # 检测时间间隔
                time-between-eviction-runs-millis: 2000

                # 8min < 链接生存期 < 10min (数据库一般会主动关闭10分钟无活动的链接)
                min-evictable-idle-time-millis: 480000
                max-evictable-idle-time-millis: 600000

                # 检测手段
                validation-query: select 1 from dual
                test-while-idle: true
                test-on-borrow: false
                test-on-return: false

                # 链接保活
                keep-alive: true

                # 缓存preparedStatement
                pool-prepared-statements: true
                max-pool-prepared-statement-per-connection-size: 100

                # 断链重连
                break-after-acquire-failure: true
                connection-error-retry-attempts: 1

                # 连接池泄漏检测。开启后对性能有影响
                remove-abandoned: false
                remove-abandoned-timeout-millis: 300000
                log-abandoned: true

                # 监控
                filters: stat,wall,log4j2
            datasource:
                master:
                    url: jdbc:oracle:thin:@//192.168.10.89:1521/his
                    username: KAOS
                    password: KAOS
mybatis-plus:
    configuration:
        default-enum-type-handler: com.kaos.walnut.core.frame.mybatis.EnumTypeHandler
        jdbc-type-for-null: "null"
    mapper-locations:
        - classpath:mapper/**/*.xml
