# web服务
server:
    port: 8080

# log4j2
logging:
    config: classpath:log4j2.yml

# spring
spring:
    mvc:
        # 关闭异常自动日志
        log-resolved-exception: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            # 访问控制界面的账号密码
            stat-view-servlet:
                enabled: true
                login-username: admin
                login-password: admin
                deny:
                allow:
                url-pattern: /druid/*
                reset-enable: true
            web-stat-filter:
                enabled: true
                url-pattern: /api/*
                exclusions: .gif,.html
        dynamic:
            primary: master
            strict: false
            druid:
                # 初始化时建立链接数量
                initial-size: 40
                # 最小连接池数量
                min-idle: 20
                # 最大连接池数量
                max-active: 60
                # 获取链接时最大等待时间，单位：毫秒
                max-wait: 5000
                # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
                test-while-idle: true
                # 既作为检测的间隔时间又作为test-While-Idel执行的依据
                time-between-eviction-runs-millis: 2000
                # 保持链接活性
                keep-alive: true
                # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
                min-evictable-idle-time-millis: 200000
                # 用来检测连接是否有效的sql 必须是一个查询语句
                validation-query: select 1 from dual
                # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
                test-on-borrow: true
                # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
                test-on-return: true
                # 是否缓存preparedStatement
                pool-prepared-statements: true
                # 当值大于0时poolPreparedStatements会自动修改为true
                max-pool-prepared-statement-per-connection-size: 100
                # 配置扩展插件
                filters: stat,wall,log4j2
                # 合并多个DruidDataSource的监控数据
                use-global-data-source-stat: false
                # 断链重连
                break-after-acquire-failure: true
                # 断链尝试次数
                connection-error-retry-attempts: 1
            datasource:
                master:
                    url: jdbc:oracle:thin:@//192.168.10.89:1521/his
                    username: KAOS
                    password: KAOS
mybatis-plus:
    configuration:
        default-enum-type-handler: com.kaos.walnut.core.frame.mybatis.EnumTypeHandler
        jdbc-type-for-null: "null"
    mapper-locations:
        - classpath:mapper/**/*.xml
